#ifndef TMESHCHECK_H__
#define TMESHCHECK_H__

enum
{
    MESHCHECK_GROUP_MAIN       = 1000,
    MESHCHECK_ENABLED          = 1001,
    MESHCHECK_ANGLE_THRESHOLD  = 1002,
    MESHCHECK_EDGE_WIDTH       = 1003,
    MESHCHECK_DEPTH_TEST       = 1004,
    MESHCHECK_USE_GRADIENT     = 1005,
    MESHCHECK_EDGE_COLOR       = 1006,
    MESHCHECK_COLOR_MIN        = 1007,
    MESHCHECK_COLOR_MAX        = 1008,
    MESHCHECK_SHOW_BOUNDARY          = 1009,
    MESHCHECK_BOUNDARY_COLOR         = 1010,
    MESHCHECK_INFO_COUNT             = 1011,
    MESHCHECK_SHOW_ANGLE             = 1012,
    MESHCHECK_SHOW_HARD_EDGES        = 1013,
    MESHCHECK_HARD_EDGE_COLOR        = 1014,
    MESHCHECK_HARD_PHONG_ANGLE       = 1015,
    MESHCHECK_SHOW_UV_SEAMS          = 1016,
    MESHCHECK_UV_SEAM_COLOR          = 1017,
    MESHCHECK_SHOW_HARD_SEAM_DIFF    = 1018,
    MESHCHECK_HARD_SEAM_COLOR        = 1019,
    MESHCHECK_ANGLE_IGNORE_HARD      = 1020
};

#endif // TMESHCHECK_H__
