#ifndef TMESHCHECK_H__
#define TMESHCHECK_H__

enum
{
    MESHCHECK_GROUP_MAIN       = 1000,
    MESHCHECK_ENABLED          = 1001,
    MESHCHECK_ANGLE_THRESHOLD  = 1002,
    MESHCHECK_EDGE_WIDTH       = 1003,
    MESHCHECK_DEPTH_TEST       = 1004,
    MESHCHECK_USE_GRADIENT     = 1005,
    MESHCHECK_EDGE_COLOR       = 1006,
    MESHCHECK_COLOR_MIN        = 1007,
    MESHCHECK_COLOR_MAX        = 1008,
    MESHCHECK_SHOW_BOUNDARY    = 1009,
    MESHCHECK_BOUNDARY_COLOR   = 1010,
    MESHCHECK_INFO_COUNT       = 1011
};

#endif // TMESHCHECK_H__
